[2023-12-08T15:45:13.808+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_airflow_dag.spark_submit_task manual__2023-12-08T15:44:48.900542+00:00 [queued]>
[2023-12-08T15:45:13.812+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_airflow_dag.spark_submit_task manual__2023-12-08T15:44:48.900542+00:00 [queued]>
[2023-12-08T15:45:13.813+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2023-12-08T15:45:13.818+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): spark_submit_task> on 2023-12-08 15:44:48.900542+00:00
[2023-12-08T15:45:13.822+0000] {standard_task_runner.py:57} INFO - Started process 250 to run task
[2023-12-08T15:45:13.825+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'spark_airflow_dag', 'spark_submit_task', 'manual__2023-12-08T15:44:48.900542+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/spark-dag-example.py', '--cfg-path', '/tmp/tmp0jd_xjhh']
[2023-12-08T15:45:13.828+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask spark_submit_task
[2023-12-08T15:45:13.838+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-12-08T15:45:13.867+0000] {task_command.py:415} INFO - Running <TaskInstance: spark_airflow_dag.spark_submit_task manual__2023-12-08T15:44:48.900542+00:00 [running]> on host dataeng-airflow-scheduler
[2023-12-08T15:45:13.916+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dibimbing' AIRFLOW_CTX_DAG_ID='spark_airflow_dag' AIRFLOW_CTX_TASK_ID='spark_submit_task' AIRFLOW_CTX_EXECUTION_DATE='2023-12-08T15:44:48.900542+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-08T15:44:48.900542+00:00'
[2023-12-08T15:45:13.922+0000] {base.py:73} INFO - Using connection ID 'spark_tgs' for task execution.
[2023-12-08T15:45:13.923+0000] {spark_submit.py:351} INFO - Spark-Submit cmd: spark-submit --master spark://dataeng-spark-master:7077 --name arrow-spark /spark-scripts/spark-example.py
[2023-12-08T15:45:15.296+0000] {spark_submit.py:521} INFO - File "/spark-scripts/spark-example.py", line 12
[2023-12-08T15:45:15.298+0000] {spark_submit.py:521} INFO - sparkcontext.setLogLevel("WARN")
[2023-12-08T15:45:15.298+0000] {spark_submit.py:521} INFO - ^
[2023-12-08T15:45:15.298+0000] {spark_submit.py:521} INFO - SyntaxError: invalid syntax
[2023-12-08T15:45:15.310+0000] {spark_submit.py:521} INFO - 23/12/08 15:45:15 INFO ShutdownHookManager: Shutdown hook called
[2023-12-08T15:45:15.312+0000] {spark_submit.py:521} INFO - 23/12/08 15:45:15 INFO ShutdownHookManager: Deleting directory /tmp/spark-797e6bcd-7759-4c1f-bd0a-874883be4246
[2023-12-08T15:45:15.341+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 160, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 452, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://dataeng-spark-master:7077 --name arrow-spark /spark-scripts/spark-example.py. Error code is: 1.
[2023-12-08T15:45:15.344+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=spark_airflow_dag, task_id=spark_submit_task, execution_date=20231208T154448, start_date=20231208T154513, end_date=20231208T154515
[2023-12-08T15:45:15.353+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task spark_submit_task (Cannot execute: spark-submit --master spark://dataeng-spark-master:7077 --name arrow-spark /spark-scripts/spark-example.py. Error code is: 1.; 250)
[2023-12-08T15:45:15.383+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-08T15:45:15.402+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
